import Link from "next/link";
import { type CatalogItem, formatMad } from "@/lib/catalog-model";
import { CatalogImage } from "./catalog-image";
import { QuickAdd, WishlistButton } from "./product-actions";
export function CatalogCard({ item }: { item: CatalogItem }) {
  const colors = [...new Set(item.variants.flatMap(variant => variant.colors))];
  const sale = item.price !== null && item.originalPrice !== null && item.originalPrice > item.price;
  const href = "/produits/" + encodeURIComponent(item.product.handle) + (item.variants.length === 1 ? "?variante=" + encodeURIComponent(item.variants[0].id) : "");
  const secondary = item.product.images.find(image => image !== item.product.thumbnail);
  return <article className="catalog-card"><div className="catalog-photo-wrap"><Link className="catalog-product-link" href={href} aria-label={"Voir " + item.product.title}><div className="product-image"><CatalogImage src={item.product.thumbnail} alt={item.product.title}/>{secondary && <div className="product-secondary"><CatalogImage src={secondary} alt={item.product.title + " — autre vue"}/></div>}{sale && <span className="product-label">Prix doux</span>}</div></Link><WishlistButton id={item.product.id} title={item.product.title}/></div><div className="catalog-card-heading"><h2><Link href={href}>{item.product.title}</Link></h2><p className="catalog-price">{item.price !== null ? <>{item.priceVaries && <span>À partir de </span>}{formatMad(item.price)}{sale && <del>{formatMad(item.originalPrice!)}</del>}</> : "Prix indisponible"}</p></div>{colors.length > 0 && <div className="color-options" aria-label="Couleurs disponibles">{colors.map(color=><span key={color} title={color}><span className="color-swatch" style={{backgroundColor:({noir:"#24201f",blanc:"#f1e9df",beige:"#cdb7a2",rose:"#c596a4",bordeaux:"#650f2c",marron:"#76513f"} as Record<string,string>)[color.toLowerCase()]||"#d8cdc4"}}/>{color}</span>)}</div>}<p className={"catalog-stock catalog-stock--" + item.stock}>{item.stock === "in_stock" ? "En stock" : item.stock === "backorder" ? "Sur commande" : item.stock === "out_of_stock" ? "Épuisé" : "Disponibilité à confirmer"}</p><QuickAdd productId={item.product.id} href={href} variants={item.variants}/></article>;
}
